clear && cargo build --release && \
# ./target/release/cs470 -p "Post-Traumatic Stress Disorder (PTSD) is a mental health condition triggered by experiencing or witnessing a traumatic event. It can develop after events such as natural disasters, serious accidents, terrorist acts, war or combat, rape, or other violent personal assaults. The disorder is characterized by intense, disturbing thoughts and feelings related to the experience that last long after the traumatic event has ended. People with PTSD may relive the event through flashbacks or nightmares; they may feel sadness, fear, or anger, and they may feel detached or estranged from other people.

# The symptoms of PTSD can be grouped into four main categories: intrusive memories, avoidance, negative changes in thinking and mood, and changes in physical and emotional reactions. Intrusive memories include recurrent, unwanted distressing memories of the traumatic event, and reliving the traumatic event as if it were happening again. Avoidance involves trying to avoid thinking or talking about the traumatic event, and avoiding places, activities, or people that remind them of the event. Negative changes in thinking and mood might include negative thoughts about oneself or others, hopelessness about the future, memory problems, and difficulty maintaining close relationships. Changes in physical and emotional reactions can manifest as being easily startled or frightened, always being on guard for danger, self-destructive behavior such as drinking too much or driving too fast, trouble sleeping, and trouble concentrating.

# The onset of PTSD symptoms can vary greatly, sometimes appearing within three months of the traumatic event, but sometimes not until years afterward. These symptoms can cause significant problems in social or work situations and in relationships. They can also interfere with one's ability to go about daily tasks. For a diagnosis of PTSD, symptoms must last more than a month and be severe enough to interfere with relationships or work.

# PTSD affects people of all ages. Women are more likely to develop PTSD than men, and certain aspects of the traumatic event, such as its severity, duration, and proximity, can also influence the development of PTSD. Not everyone who experiences trauma develops PTSD, as factors like genetic predisposition, previous history of trauma, and the presence of a strong support system play a role.

# Treatment for PTSD typically involves psychotherapy, medication, or a combination of the two. Cognitive-behavioral therapy (CBT) is particularly effective, focusing on changing the patterns of thinking or behavior that are causing people’s problems. Medications, such as antidepressants, can help control PTSD symptoms. Living with PTSD can be challenging, but treatment and support can significantly improve the quality of life for those affected by this disorder. It is important for individuals experiencing PTSD symptoms to seek help from a mental health professional."
./target/release/cs470 --temperature 0.2 -p "The events of September 11, 2001, commonly referred to as 9/11, mark a significant and tragic day in history. On that morning, 19 terrorists associated with the extremist group al-Qaeda hijacked four commercial airplanes. These hijackers aimed to carry out suicide attacks against major landmarks in the United States.

The first two planes, American Airlines Flight 11 and United Airlines Flight 175, were flown into the North and South Towers of the World Trade Center in New York City. The impacts caused massive explosions and fires, leading to the collapse of both towers within less than two hours. This attack resulted in the deaths of thousands of people, including workers in the buildings, emergency responders, and the passengers on the planes.

A third plane, American Airlines Flight 77, was hijacked and flown into the Pentagon, the headquarters of the United States Department of Defense, located in Arlington, Virginia. This attack caused significant structural damage to the building and resulted in the deaths of 125 military and civilian personnel, in addition to the 59 passengers and crew on the plane.

The fourth plane, United Airlines Flight 93, was also hijacked and was believed to be headed towards another target in Washington, D.C., possibly the White House or the U.S. Capitol. However, passengers on Flight 93 fought back against the hijackers, leading to the plane crashing into a field near Shanksville, Pennsylvania. All 44 people on board were killed, but their actions prevented further destruction and loss of life at the intended target.

In total, nearly 3,000 people were killed in the 9/11 attacks, and thousands more were injured. The attacks had a profound impact on the United States and the world, leading to widespread fear, grief, and anger. In response, the U.S. government launched the War on Terror, initiating military operations in Afghanistan to dismantle al-Qaeda and remove the Taliban regime that harbored them. This conflict expanded over the years, impacting international relations, security policies, and leading to prolonged military engagements in the Middle East.

Domestically, 9/11 led to significant changes in U.S. security policies and practices. The Department of Homeland Security was established to coordinate national efforts against terrorism, and the USA PATRIOT Act was enacted, expanding surveillance and investigative powers for law enforcement agencies. Airport security was drastically overhauled, with the creation of the Transportation Security Administration (TSA) and the implementation of more stringent screening procedures for passengers and baggage.

The memory of 9/11 is preserved through various memorials and annual ceremonies. The National September 11 Memorial & Museum in New York City stands at the site of the World Trade Center, honoring the lives lost and the heroism of the first responders. The Pentagon Memorial and the Flight 93 National Memorial also serve as places of remembrance and reflection.

9/11 fundamentally changed the geopolitical landscape and had lasting effects on international relations, security policies, and societal attitudes towards terrorism. The unity and resilience shown in the aftermath of the attacks, along with the ongoing efforts to prevent future acts of terrorism, continue to shape the global approach to security and peace."
